---
abstract: L10N Message Retrieval
author: 'Yung-chung Lin <henearkrxern@gmail.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Locale-Memories
no_index:
  directory:
    - inc
    - t
requires:
  Locale::PO: 0
  Search::Xapian: 0
version: 0.01
